#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <bucket-name>"
    exit 1
fi
BUCKET_NAME=$1
REGION="us-east-1"
echo "Creating S3 bucket: $BUCKET_NAME..."
aws s3 mb s3://$BUCKET_NAME --region $REGION
echo "Configuring bucket settings..."
aws s3api put-public-access-block --bucket $BUCKET_NAME --public-access-block-configuration BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false
echo "Enabling ACLs and setting bucket ownership..."
aws s3api put-bucket-ownership-controls --bucket $BUCKET_NAME --ownership-controls Rules=[{ObjectOwnership=BucketOwnerPreferred}]
echo "Applying bucket policy to allow public read access..."
cat <<EOT > bucket-policy.json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::$BUCKET_NAME/*"
        }
    ]
}
EOT
aws s3api put-bucket-policy --bucket $BUCKET_NAME --policy file://bucket-policy.json
echo "Enabling static website hosting..."
aws s3 website s3://$BUCKET_NAME/ --index-document index.html --error-document error.html
echo "Downloading and uploading a sample index.html file..."
curl -o index.html https://s3.amazonaws.com/ds2002-resources/labs/lab4/index.html
aws s3 cp index.html s3://$BUCKET_NAME/ --acl public-read
echo "Your static website is now available at:"
echo "http://$BUCKET_NAME.s3-website-$REGION.amazonaws.com/"
